### ISSUE TITLE
Parsing firmware.json failed on every log

### ISSUE THREAD

**Issue by SuperOkazaki** [stonegray/MacEasySaveSHSH#2]
All log files have this:

```
[TSSC] manually specified ecid to use, parsed "000003364C32F6AC" to dec:3531741525676 hex:3364c32f6ac
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] parsing firmware.json failed
```

I can't get my SSH :/

**Comment by SuperOkazaki** [comment]
Tried again without the 00000 in front of the ECID, still no luck

**Comment by stonegray** [comment]
/u/dolopodog has suggested adding a certificate. I've added this to the script in 0ecee3d2a5492c7ba9c72011209f769778d3c049, but commented out because I'm iffy on auto-installing certs on people's machines. Uncomment line 6 to use it. 

Some info in Edit 2 here: https://www.reddit.com/r/jailbreak/comments/5injzb/tutorial_how_to_get_shsh2_for_1011_with/

**Comment by SuperOkazaki** [comment]
I'm getting an error telling me that Keychain Access couldn't import the item

**Comment by stonegray** [comment]
Can you run `curl -L https://api.ipsw.me/v2.1/firmwares.json >>  firmwares.json` and upload the output?

**Comment by SuperOkazaki** [comment]
[This is what the output looks like](http://i.imgur.com/Ic40HJh.png)

**Comment by stonegray** [comment]
Should have written a file called firmware.json, can you upload that here? I can't get the same error on my end.

**Comment by SuperOkazaki** [comment]
Where would it have written to? Where the current working directory was? I didn't have one.

**Comment by SuperOkazaki** [comment]
Nevermind. Hold on

**Comment by SuperOkazaki** [comment]
Here it is. Was too big for pastebin.
https://a.pomf.cat/baxvkq.json

**Comment by stonegray** [comment]
Can you try this branch? https://github.com/stonegray/MacEasySaveSHSH/tree/firmware-json-fix 

That should do it

**Comment by SuperOkazaki** [comment]
Same :( 
`[TSSC] manually specified ecid to use, parsed "3364C32F6AC" to dec:3531741525676 hex:3364c32f6ac
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[Error] [TSSC] parsing firmware.json failed
`

**Comment by stonegray** [comment]
What model is your phone?

**Comment by SuperOkazaki** [comment]
6s+, iPhone8,2

**Comment by stonegray** [comment]
Problem is with the TSSChecker tool, appears specific to the 6s+

Closing the issue because it's not in the script, but I'll keep working on this.

**Comment by SuperOkazaki** [comment]
Damn. Thanks for the help though. I appreciate it. I'm just going to go ahead and bite the bullet and go to 10.1.1 now.

**Comment by stonegray** [comment]
[iPhone6,2 3364C32F6AC SuperOkazaki.zip](https://github.com/stonegray/MacEasySaveSHSH/files/658432/iPhone6.2.3364C32F6AC.SuperOkazaki.zip)

Got your blobs here in case you haven't updated. 

Turns out TSSChecker needs to have the IPSWs downloaded to do certain firmwares.

**Comment by SuperOkazaki** [comment]
Thanks!
