### ISSUE TITLE
error logs

### ISSUE THREAD

**Issue by mykamel** [stonegray/MacEasySaveSHSH#3]
[log_10_1_1_100.txt](https://github.com/stonegray/MacEasySaveSHSH/files/658354/log_10_1_1_100.txt)
[log_10_1_1_150.txt](https://github.com/stonegray/MacEasySaveSHSH/files/658355/log_10_1_1_150.txt)
[log_10_1.txt](https://github.com/stonegray/MacEasySaveSHSH/files/658356/log_10_1.txt)
[log_10_2.txt](https://github.com/stonegray/MacEasySaveSHSH/files/658357/log_10_2.txt)
[log.txt](https://github.com/stonegray/MacEasySaveSHSH/files/658358/log.txt)

**Comment by mykamel** [comment]
[log_10_1_1_100.txt](https://github.com/stonegray/MacEasySaveSHSH/files/658376/log_10_1_1_100.txt)
[log_10_1_1_150.txt](https://github.com/stonegray/MacEasySaveSHSH/files/658379/log_10_1_1_150.txt)
[log_10_1.txt](https://github.com/stonegray/MacEasySaveSHSH/files/658378/log_10_1.txt)
[log_10_2.txt](https://github.com/stonegray/MacEasySaveSHSH/files/658377/log_10_2.txt)

**Comment by stonegray** [comment]
TSSChecker is trying to download the entire 10.1.1b150 IPSW, so give me 20 minutes or so to figure it out.

**Comment by stonegray** [comment]
Taking longer, haven't forgotten

**Comment by mykamel** [comment]
Thanks , not a big hurry... Just hope it didnt download the whole thing on my hotspot :( otherwise I'll be throttled by the end of the month.

**Comment by stonegray** [comment]
[iPhone7,1 3977947706954426.zip](https://github.com/stonegray/MacEasySaveSHSH/files/658484/iPhone7.1.3977947706954426.zip)
 
Only downloaded on my end. Enjoy!

**Comment by mykamel** [comment]
Thanks!
