### ISSUE TITLE
Use latest tsschecker

### ISSUE THREAD

**Issue by ddaddy** [stonegray/MacEasySaveSHSH#5]
There is a version 1.0.6 of tsschecker available.

**Comment by stonegray** [comment]
Heard some reported issues with 1.0.6 were resolved with 1.0.5, deliberately using older version for stability. 

You can change the 1.0.5 to 1.0.6 in the source, no other changes are needed to use the new version.

**Comment by ddaddy** [comment]
ah ok, no worries. I just noticed there was a newer version.

**Comment by stonegray** [comment]
Ideally we'd update for the bugfixes in 1.0.6 but I don't have time to check it to see if it's stable across platforms. 

If you want to take that on, I'll merge your change in. El Capitan seems to be the most problematic from what I've heard.

**Comment by ddaddy** [comment]
It's only a crash fix, so I think it's fine.
